---
- name: Install Docker dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker's official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker
  become: yes
  apt:
    name: docker-ce
    state: present

- name: Add the current user to the docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes



   


