---
- name: create the ansible user account
  become: yes
  user: name=ansible append=yes state=present createhome=yes shell=/bin/bash
  
- name: allow 'ansible' to use sudo without needing a password
  become: yes
  lineinfile:
      dest: /etc/sudoers
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'


- name: Set Authorized key taken from file
  become: yes
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    