---
- name: Deploy Mealie with Docker Compose
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Copy docker-compose.yml file
      copy:
        src: docker-compose.yml
        dest: /home/katelyna/CDW-homelab/docker/

    - name: Start Mealie container
      environment:
        COMPOSE_INTERACTIVE_NO_CLI: '1' 
      command: docker-compose up -d
      args:
        chdir: .

