---

  - name: workstation base packages
    hosts: all 
    become: yes
    tasks: 
      - name: packages
        apt:
          update_cache: yes
          name:
            - cowsay
            - ansible
          state: present
