name: Super Linter Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    env:
      SECRET_ENCRYPTION_KEY: ${{ secrets.SECRET_ENCRYPTION_KEY }} # Inject secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Prettier
        run: |
          npm install --global prettier
          prettier --check .

      - name: Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
